import requests


class ResponseBuilder:

    def __init__(self):
        self.url = "http://localhost:11434/api/generate"
        self.model = "llama3.2:latest"

    def build(self, responses):

        if not responses:
            return "No response generated."

        llm_outputs = ""

        for item in responses:
            llm_outputs += (
                f"Task: {item['task']}\n"
                f"Response: {item['response']}\n\n"
            )

        prompt = f"""
You are the final response builder of an AI Gateway.

The following outputs were generated by different AI models.

{llm_outputs}

Your job is to synthesize these outputs into a single coherent response.

Requirements:
- Write one fluent paragraph.
- Merge the information naturally.
- Remove duplicate information.
- Do not mention tasks.
- Do not mention models.
- Do not mention providers.
- Do not start with phrases like "Here's the combined response".
- Return only the final answer.
"""

        response = requests.post(
            self.url,
            json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }
        )

        if response.status_code != 200:
            return "Failed to generate final response."

        try:
            return response.json()["response"].strip()
        except Exception:
            return "Failed to parse final response."



