from app.providers.base import BaseProvider

class MockFastProvider(BaseProvider):

    def generate(self, prompt: str) -> str:

        prompt = prompt.lower()

        if "summary" in prompt or "summarize" in prompt:
            return "This is a mock summary generated by Mock Fast Provider."

        elif "classify" in prompt or "classification" in prompt:
            return "Mock classification result: Positive."

        elif "extract" in prompt or "data" in prompt:
            return "Mock extracted data: Name - John, Age - 25."

        else:
            return "Mock Fast Provider processed your request successfully."



        